import { Brain, Info, Sparkles } from "lucide-react";
import type {
  Narrative,
  NarrativeChip,
  NarrativeExplainItem,
  NarrativeSection,
  NarrativeSectionStatus,
  SeverityTone,
} from "@/types/ai-agent/ai_summary_types";

/**
 * Narrative summary card matching the mockup's `.narrative` block.
 *
 * Spec sources (`New Ui/2 Health Analysis/.../css/styles.css`):
 *   - .narr-section: padding 26px 0, bottom border per section
 *   - .narr-h: serif 22 / 700 / accent-dark
 *   - .narr-status: mono 11.5 / 0.12em / padding 6px 12px / rounded-full
 *   - .narr-chip: surface-2 bg, padding 11/15, radius 9, font 16
 *   - .narr-p: 17px / 1.62 / ink-2
 *   - .narr-explain: border-left 3 ink-3, padding 4/0/6/20 (not boxed)
 *   - .narr-explain-h: 17 / 700 / ink
 *   - .narr-explain-item: 16 / 1.65, .range surface-2 12.5 mono 2/8 radius 4
 */
export default function NarrativeReportCard({
  narrative,
}: {
  narrative: Narrative | null;
}) {
  if (!narrative || narrative.sections.length === 0) {
    return (
      <div
        id="narrative-report"
        className="apex-card mb-[18px] scroll-mt-20"
        style={{ padding: "6px 30px 30px" }}
      >
        <Header />
        <p className="text-[15px] text-ink-2 mt-4">
          No narrative available. Run a new analysis to generate one.
        </p>
      </div>
    );
  }

  return (
    <div
      id="narrative-report"
      className="apex-card mb-[18px] scroll-mt-20 overflow-hidden"
    >
      {/* Mock card-head: title + ApexAI tag */}
      <div
        className="flex items-baseline justify-between gap-3"
        style={{ padding: "18px 22px 14px", borderBottom: "1px solid var(--line)" }}
      >
        <h3
          className="font-mono inline-flex items-center gap-1.5 uppercase m-0"
          style={{
            fontSize: 13,
            letterSpacing: "0.12em",
            color: "var(--ink-2)",
            fontWeight: 600,
          }}
        >
          <Brain
            style={{ width: 15, height: 15, color: "var(--apex-accent-bright)" }}
            strokeWidth={1.8}
          />
          Narrative summary
        </h3>
        <span
          className="font-mono inline-flex items-center gap-1.5 uppercase"
          style={{
            fontSize: 12.5,
            letterSpacing: "0.04em",
            color: "var(--ink-3)",
          }}
        >
          <Sparkles className="w-3 h-3" strokeWidth={2} />
          Generated by ApexAI
        </span>
      </div>

      {/* Narrative inner — mockup uses .narrative wrapper with px 30 py 6/30 */}
      <div style={{ padding: "6px 30px 30px" }}>
        {narrative.sections.map((section) => (
          <SectionBlock key={section.id} section={section} />
        ))}
      </div>
    </div>
  );
}

function Header() {
  return (
    <div
      className="flex items-baseline justify-between gap-3"
      style={{ padding: "18px 0 14px", borderBottom: "1px solid var(--line)" }}
    >
      <h3
        className="font-mono inline-flex items-center gap-1.5 uppercase m-0"
        style={{
          fontSize: 13,
          letterSpacing: "0.12em",
          color: "var(--ink-2)",
          fontWeight: 600,
        }}
      >
        <Brain
          style={{ width: 15, height: 15, color: "var(--apex-accent-bright)" }}
          strokeWidth={1.8}
        />
        Narrative summary
      </h3>
    </div>
  );
}

// ─── Section ─────────────────────────────────────────────────────────────

function SectionBlock({ section }: { section: NarrativeSection }) {
  return (
    <section
      className="border-b border-[var(--line)] last:border-b-0"
      style={{ padding: "26px 0" }}
    >
      {/* narr-section-head */}
      <div className="flex items-center justify-between gap-3.5 mb-4 flex-wrap">
        <h4
          className="font-sans m-0 inline-flex items-center gap-2.5"
          style={{
            fontSize: 22,
            fontWeight: 700,
            letterSpacing: "-0.015em",
            color: "var(--apex-accent-dark)",
          }}
        >
          {section.title}
        </h4>
        <StatusPill status={section.status} />
      </div>

      {/* narr-chips */}
      {section.chips.length > 0 && (
        <div className="flex flex-wrap gap-2 mb-4">
          {section.chips.map((chip, i) => (
            <ChipPill key={`${chip.label}-${i}`} chip={chip} />
          ))}
        </div>
      )}

      {/* narr-p */}
      {section.paragraph && (
        <p
          className="m-0 mb-2.5 last:mb-0"
          style={{ fontSize: 17, lineHeight: 1.62, color: "var(--ink-2)" }}
        >
          {section.paragraph}
        </p>
      )}

      {/* narr-explain — border-left, always visible per mockup (no toggle) */}
      {section.explainItems.length > 0 && (
        <div
          className="mt-[18px]"
          style={{
            padding: "4px 0 6px 20px",
            borderLeft: "3px solid var(--ink-3)",
          }}
        >
          <div className="flex items-center gap-2 mb-3.5">
            <Info
              style={{ width: 18, height: 18, color: "var(--ink-3)" }}
              strokeWidth={1.9}
            />
            <span
              className="font-sans"
              style={{
                fontSize: 17,
                fontWeight: 700,
                letterSpacing: "-0.01em",
                color: "var(--ink)",
              }}
            >
              What this means in plain terms
            </span>
          </div>
          <ul className="flex flex-col gap-3.5">
            {section.explainItems.map((item, i) => (
              <li key={`${item.name}-${i}`}>
                <ExplainRow item={item} />
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}

function ExplainRow({ item }: { item: NarrativeExplainItem }) {
  return (
    <div
      className="flex flex-col gap-1.5"
      style={{ fontSize: 16, lineHeight: 1.65, color: "var(--ink)" }}
    >
      <div className="inline-flex items-baseline gap-2 flex-wrap">
        <strong style={{ fontWeight: 700 }}>{item.name}</strong>
        {item.referenceRange && (
          <span
            className="font-mono"
            style={{
              background: "var(--surface-2)",
              color: "var(--ink-2)",
              padding: "2px 8px",
              borderRadius: 4,
              fontSize: 12.5,
              fontWeight: 600,
              letterSpacing: "0.02em",
              whiteSpace: "nowrap",
            }}
          >
            {item.referenceRange}
          </span>
        )}
      </div>
      <p style={{ margin: 0 }}>{item.explanation}</p>
    </div>
  );
}

// ─── Pills ───────────────────────────────────────────────────────────────

function StatusPill({ status }: { status: NarrativeSectionStatus }) {
  return (
    <span
      className="font-mono uppercase inline-flex items-center gap-1.5 rounded-full whitespace-nowrap"
      style={{
        background: toneSoft(status.tone),
        color: toneSolid(status.tone),
        padding: "6px 12px",
        fontSize: 11.5,
        fontWeight: 600,
        letterSpacing: "0.12em",
      }}
    >
      <span
        className="w-1.5 h-1.5 rounded-full"
        style={{ background: toneSolid(status.tone) }}
      />
      {status.label}
    </span>
  );
}

function ChipPill({ chip }: { chip: NarrativeChip }) {
  return (
    <span
      className="inline-flex items-center gap-2.5 rounded-[9px]"
      style={{
        background: "var(--surface-2)",
        padding: "11px 15px",
        fontSize: 16,
        lineHeight: 1,
      }}
    >
      <span style={{ color: "var(--ink-2)", fontWeight: 400 }}>{chip.label}</span>
      <span
        className="font-mono tabular-nums"
        style={{
          color: "var(--ink)",
          fontWeight: 600,
          letterSpacing: "-0.01em",
        }}
      >
        {chip.value}
        {chip.unit && (
          <span
            className="font-sans"
            style={{
              color: "var(--ink-3)",
              fontSize: 13.5,
              marginLeft: 3,
              fontWeight: 400,
            }}
          >
            {chip.unit}
          </span>
        )}
      </span>
      <span
        className="w-2 h-2 rounded-full shrink-0"
        style={{ background: toneSolid(chip.tone) }}
      />
    </span>
  );
}

// ─── Tone palette ────────────────────────────────────────────────────────

function toneSolid(tone: SeverityTone): string {
  switch (tone) {
    case "opt":
      return "var(--opt)";
    case "bord":
      return "var(--bord)";
    case "att":
      return "var(--att)";
  }
}
function toneSoft(tone: SeverityTone): string {
  switch (tone) {
    case "opt":
      return "var(--opt-soft)";
    case "bord":
      return "var(--bord-soft)";
    case "att":
      return "var(--att-soft)";
  }
}
