// @ts-nocheck
export const portalEnvironments = [
  {
    id: "apex-md",
    name: "Apex MD",
    slug: "apex-md",
    logoUrl: "https://media.api.com/images/public/68dc2f71f36b75ec180e03bd/61e8b3af9_ApexMdlrgsymsideblack.png",
    primaryColor: "#9B1C2E",
    secondaryColor: "#1A1A1A",
    accentColor: "#F5E4E7",
    backgroundColor: "#FFFFFF",
    surfaceColor: "#FFFFFF",
    surface2Color: "#EAEAE7",
    textColor: "#1A1A1A",
    mutedTextColor: "#8A8A8A",
    borderColor: "#E8E8E8",
    sidebarBg: "#FFFFFF",
    sidebarText: "#525252",
    buttonStyle: "solid",
    themeMode: "light",
    aiEnabled: true,
    aiPromptContext: "You are an AI assistant for Apex MD, a premium medical wellness and health optimization platform. Focus on bloodwork interpretation, hormone optimization, performance, and medical-grade wellness guidance. Be precise, evidence-based, and clinically informative.",
    aiDisclaimer: "This AI assistant provides educational information and is not a substitute for medical advice, diagnosis, or treatment.",
    aiAllowedTopics: ["bloodwork", "medications", "fitness", "recovery", "wellness", "hormones", "nutrition"],
  },
  {
    id: "planet-fitness",
    name: "Planet Fitness",
    slug: "planet-fitness",
    logoUrl: "https://media.api.com/images/public/68dc2f71f36b75ec180e03bd/a1cef0d47_image.png",
    primaryColor: "#F5EB2F",
    secondaryColor: "#A5268D",
    accentColor: "#F5EB2F",
    backgroundColor: "#FFFFFF",
    surfaceColor: "#F5F5F5",
    textColor: "#1A1A2E",
    mutedTextColor: "#555566",
    borderColor: "#E0E0EE",
    sidebarBg: "#FFFFFF",
    sidebarText: "#1A1A2E",
    buttonStyle: "solid",
    themeMode: "light",
    aiEnabled: true,
    aiPromptContext: "You are an AI fitness assistant for Planet Fitness members. Be approachable, supportive, motivating, and accessible. Focus on fitness education, workout guidance, recovery tips, and general wellness. Make members feel welcome and encouraged regardless of their fitness level.",
    aiDisclaimer: "This AI assistant provides educational fitness information and is not a substitute for medical advice.",
    aiAllowedTopics: ["bloodwork", "medications", "fitness", "recovery", "wellness", "workouts", "nutrition"],
  },
  {
    id: "golds-gym",
    name: "Gold's Gym",
    slug: "golds-gym",
    logoUrl: "https://media.api.com/images/public/68dc2f71f36b75ec180e03bd/374dd8690_image.png",
    primaryColor: "#FDEB00",
    secondaryColor: "#1B1918",
    accentColor: "#C7B905",
    backgroundColor: "#FFFFFF",
    surfaceColor: "#F5F5F5",
    textColor: "#1B1918",
    mutedTextColor: "#666666",
    borderColor: "#E0E0E0",
    sidebarBg: "#FFFFFF",
    sidebarText: "#1B1918",
    buttonStyle: "solid",
    themeMode: "light",
    aiEnabled: true,
    aiPromptContext: "You are an AI performance assistant for Gold's Gym members. Be confident, direct, performance-focused, and motivating. Focus on strength training, muscle building, recovery, nutrition, and peak performance. Speak to serious fitness enthusiasts who want results.",
    aiDisclaimer: "This AI assistant provides educational fitness and wellness information and is not a substitute for medical advice.",
    aiAllowedTopics: ["bloodwork", "medications", "fitness", "recovery", "wellness", "strength", "nutrition"],
    storeLinks: {
      base: "https://formgolds.apexmd.com",
      quizUrls: {
        "weight-loss": "https://formgolds.apexmd.com?categoryId=weight-loss",
        "trt": "https://formgolds.apexmd.com?categoryId=trt",
        "hrt": "https://formgolds.apexmd.com?categoryId=hrt",
        "longevity": "https://formgolds.apexmd.com",
        "peptides": "https://formgolds.apexmd.com",
        "labs": "https://formgolds.apexmd.com?productid=labs-only",
      },
      productUrls: {
        // Weight Loss
        "compounded-semaglutide": "https://formgolds.apexmd.com?productid=compounded-semaglutide",
        "compounded-tirzepatide": "https://formgolds.apexmd.com?productid=compounded-tirzepatide",
        "semaglutide-odt": "https://formgolds.apexmd.com?productid=semaglutide-odt",
        "tirzepatide-odt": "https://formgolds.apexmd.com?productid=tirzepatide-odt",
        "compounded-semaglutide-micro": "https://formgolds.apexmd.com?productid=compounded-semaglutide-micro",
        "compounded-tirzepatide-micro": "https://formgolds.apexmd.com?productid=compounded-tirzepatide-micro",
        "semaglutide-odt-micro": "https://formgolds.apexmd.com?productid=semaglutide-odt-micro",
        "tirzepatide-odt-micro": "https://formgolds.apexmd.com?productid=tirzepatide-odt-micro",
        // TRT
        "testosterone-cream": "https://formgolds.apexmd.com?productid=testosterone-cream",
        "testosterone-replacement-injection": "https://formgolds.apexmd.com?productid=testosterone-replacement-injection",
        "testosterone-troche": "https://formgolds.apexmd.com?productid=testosterone-troche",
        "kyzatrex": "https://formgolds.apexmd.com?productid=kyzatrex",
        "gonadorelin-odt": "https://formgolds.apexmd.com?productid=gonadorelin-odt",
        "testosterone-gel": "https://formgolds.apexmd.com?productid=testosterone-gel",
        "enclomiphene": "https://formgolds.apexmd.com?productid=enclomiphene",
        // HRT
        "estradiol-olive-oil-pill-capsule": "https://formgolds.apexmd.com?productid=estradiol-olive-oil-pill-capsule",
        "estradiol-cream": "https://formgolds.apexmd.com?productid=estradiol-cream",
        "estradiol-patch": "https://formgolds.apexmd.com?productid=estradiol-patch",
        "estriol-cream": "https://formgolds.apexmd.com?productid=estriol-cream",
        // Longevity
        "nad-injection": "https://formgolds.apexmd.com?productid=nad-injection",
        "nad-nasal-spray": "https://formgolds.apexmd.com?productid=nad-nasal-spray",
        "sermorelin-injection": "https://formgolds.apexmd.com?productid=sermorelin-injection",
        "sermorelin-odt": "https://formgolds.apexmd.com?productid=sermorelin-odt",
        "b12-mic": "https://formgolds.apexmd.com?productid=b12-mic",
        // Peptides
        "cjc-ipamorelin": "https://formgolds.apexmd.com?productid=cjc-ipamorelin",
        "wolverine-stack": "https://formgolds.apexmd.com?productid=wolverine-stack",
        "glow-stack": "https://formgolds.apexmd.com?productid=glow-stack",
        "bpc-157-injection": "https://formgolds.apexmd.com?productid=bpc-157-injection",
        "tb-500-injection": "https://formgolds.apexmd.com?productid=tb-500-injection",
        "pt-141-injection": "https://formgolds.apexmd.com?productid=pt-141-injection",
        "ghk-cu-cream": "https://formgolds.apexmd.com?productid=ghk-cu-cream",
        // Labs
        "labs-only": "https://formgolds.apexmd.com?productid=labs-only",
      },
    },
  },
  {
    id: "defined-fitness",
    name: "Defined Fitness",
    slug: "defined-fitness",
    logoUrl: "https://media.api.com/images/public/68dc2f71f36b75ec180e03bd/daf223177_image.png",
    primaryColor: "#CC1F24",
    secondaryColor: "#565656",
    accentColor: "#CC1F24",
    backgroundColor: "#FFFFFF",
    surfaceColor: "#F5F5F5",
    textColor: "#2B2B2B",
    mutedTextColor: "#565656",
    borderColor: "#E0E0E0",
    sidebarBg: "#FFFFFF",
    sidebarText: "#2B2B2B",
    buttonStyle: "solid",
    themeMode: "light",
    aiEnabled: true,
    aiPromptContext: "You are an AI performance assistant for Defined Fitness members. Be energetic, results-driven, and motivating. Focus on strength training, body composition, recovery, nutrition, and helping members reach their defined fitness goals.",
    aiDisclaimer: "This AI assistant provides educational fitness and wellness information and is not a substitute for medical advice.",
    aiAllowedTopics: ["bloodwork", "medications", "fitness", "recovery", "wellness", "strength", "nutrition"],
  },
  {
    id: "eos-fitness",
    name: "EōS Fitness",
    slug: "eos-fitness",
    logoUrl: "https://media.api.com/images/public/68dc2f71f36b75ec180e03bd/76d71f583_image.png",
    primaryColor: "#2AA8E0",
    secondaryColor: "#1A1A1A",
    accentColor: "#2AA8E0",
    backgroundColor: "#FFFFFF",
    surfaceColor: "#F5F5F5",
    textColor: "#1A1A1A",
    mutedTextColor: "#555555",
    borderColor: "#E0E0E0",
    sidebarBg: "#FFFFFF",
    sidebarText: "#000000",
    buttonStyle: "solid",
    themeMode: "light",
    aiEnabled: true,
    aiPromptContext: "You are an AI fitness assistant for EōS Fitness members. Be energetic, welcoming, and fitness-focused. Help members with workout guidance, healthy lifestyle tips, recovery, and general wellness questions. Encourage members of all fitness levels to reach their goals.",
    aiDisclaimer: "This AI assistant provides educational fitness and wellness information and is not a substitute for medical advice.",
    aiAllowedTopics: ["bloodwork", "medications", "fitness", "recovery", "wellness", "lifestyle", "nutrition"],
  },
  {
    id: "onelife-fitness",
    name: "OneLife Fitness",
    slug: "onelife-fitness",
    logoUrl: "https://media.api.com/images/public/68dc2f71f36b75ec180e03bd/b97aca57b_image.png",
    primaryColor: "#0C6297",
    secondaryColor: "#E05F2B",
    accentColor: "#EB9437",
    backgroundColor: "#F7F8FA",
    surfaceColor: "#FFFFFF",
    textColor: "#2D3138",
    mutedTextColor: "#6B7280",
    borderColor: "#E5E7EB",
    sidebarBg: "#0C6297",
    sidebarText: "#FFFFFF",
    buttonStyle: "solid",
    themeMode: "light",
    aiEnabled: true,
    aiPromptContext: "You are an AI wellness assistant for OneLife Fitness members. Be modern, encouraging, and wellness-focused. Help members with fitness guidance, healthy lifestyle tips, recovery, and general wellness questions in a friendly, easy-to-understand way.",
    aiDisclaimer: "This AI assistant provides educational wellness information and is not a substitute for medical advice.",
    aiAllowedTopics: ["bloodwork", "medications", "fitness", "recovery", "wellness", "lifestyle", "nutrition"],
  },
];

export const getEnvironmentById = (id) =>
  portalEnvironments.find((e) => e.id === id) || portalEnvironments[0];

export const defaultEnvironment = portalEnvironments[0];