// Refresh time counter
  let refreshSec = 0;
  setInterval(() => {
    refreshSec += 1;
    const el = document.getElementById('refreshTime');
    if (el) el.textContent = refreshSec < 5 ? 'live' : `${refreshSec}s ago`;
  }, 1000);

  // History row click → swap active
  document.querySelectorAll('.history-row').forEach(row => {
    row.addEventListener('click', () => {
      document.querySelectorAll('.history-row').forEach(r => r.classList.remove('active'));
      row.classList.add('active');
    });
  });

  // Chat input enter → log (demo)
  const chatInput = document.querySelector('.chat-dock input');
  const sendBtn = document.querySelector('.chat-dock .send-btn');
  function handleSend() {
    const val = chatInput.value.trim();
    if (!val) return;
    // demo behavior: clear and pulse the button
    chatInput.value = '';
    sendBtn.style.transform = 'scale(0.9)';
    setTimeout(() => sendBtn.style.transform = '', 150);
  }
  sendBtn.addEventListener('click', handleSend);
  chatInput.addEventListener('keydown', (e) => { if (e.key === 'Enter') handleSend(); });

/* ============================================================ */

// -------- PDF Report Builder --------
  function buildReport() {
    const reportId = 'HA-2026-Q2-RC';
    const generatedAt = 'May 12, 2026 · 9:14 AM PT';

    const _thumbs = [...document.querySelectorAll('.reco-item .reco-thumb img')].map(i => i.getAttribute('src') || '');
    const _docPhoto = (document.querySelector('.concierge-photo img') || {}).getAttribute ? (document.querySelector('.concierge-photo img').getAttribute('src') || '') : '';

    const r = document.getElementById('pdfReport');
    r.innerHTML = `

    <!-- ===================== PAGE 1: COVER + SCORES ===================== -->
    <section class="pdf-page">
      ${headerHTML(reportId, 1)}

      <h1 class="pdf-doc-title">Health <em>analysis</em> report</h1>
      <p class="pdf-doc-sub">Personalized longitudinal insights from your latest lab work, generated by ApexAI and reviewed by your physician.</p>

      <div class="pdf-patient">
        <div class="pdf-patient-field">
          <span class="pdf-patient-label">Patient</span>
          <span class="pdf-patient-value">Randall Chen</span>
        </div>
        <div class="pdf-patient-field">
          <span class="pdf-patient-label">Member ID</span>
          <span class="pdf-patient-value">APX-7834-RC</span>
        </div>
        <div class="pdf-patient-field">
          <span class="pdf-patient-label">Plan</span>
          <span class="pdf-patient-value">Apex Longevity · Active</span>
        </div>
        <div class="pdf-patient-field">
          <span class="pdf-patient-label">DOB / Age</span>
          <span class="pdf-patient-value">Jan 15, 1986 · 40 yrs</span>
        </div>
        <div class="pdf-patient-field">
          <span class="pdf-patient-label">Lab drawn</span>
          <span class="pdf-patient-value">May 11, 2026 · 6:26 AM</span>
        </div>
        <div class="pdf-patient-field">
          <span class="pdf-patient-label">Lab source</span>
          <span class="pdf-patient-value">LabCorp + Quest</span>
        </div>
        <div class="pdf-patient-field">
          <span class="pdf-patient-label">Ordering provider</span>
          <span class="pdf-patient-value">Jim Bowen, MD</span>
        </div>
        <div class="pdf-patient-field">
          <span class="pdf-patient-label">Generated</span>
          <span class="pdf-patient-value">May 12, 2026</span>
        </div>
      </div>

      <div class="pdf-h">Overall health score <span class="right">+1 vs May 6 · 86th %ile age cohort</span></div>
      <div class="pdf-score-row">
        <div class="pdf-donut-wrap">
          ${donutSVG(89)}
          <div class="pdf-donut-label">Composite · Good</div>
        </div>
        <div class="pdf-bdown">
          ${bdownRow('Metabolic', 89)}
          ${bdownRow('Cardiovascular', 95)}
          ${bdownRow('Renal', 78, 'warn')}
          ${bdownRow('Endocrine', 83)}
          ${bdownRow('Hematology', 92)}
          ${bdownRow('Micronutrients', 97)}
        </div>
      </div>

      <div class="pdf-two-col">
        <div class="pdf-mini-card">
          <div class="pdf-mini-card-title">Biological age</div>
          <div class="pdf-mini-card-big">36.4<span class="unit">yrs</span></div>
          <div class="pdf-mini-card-sub">↓ 3.6 yrs younger than chronological (40 yrs)</div>
          <div class="pdf-mini-card-foot">Trajectory · 36.6 → 36.5 → 36.4 &nbsp;|&nbsp; PhenoAge · 9 biomarkers · Levine 2018</div>
        </div>
        <div class="pdf-mini-card">
          <div class="pdf-mini-card-title">Biomarker status</div>
          <div class="pdf-mini-card-big">21<span class="unit">/ 27 optimal</span></div>
          <div class="pdf-mini-card-sub" style="color:#B8761C">⚠ 6 markers flagged for follow-up</div>
          <div class="pdf-mini-card-foot">Composite scored on 27 markers across 6 subsystems</div>
        </div>
      </div>

      ${pageFooter(1, 5, reportId, generatedAt)}
    </section>

    <!-- ===================== PAGE 2: CHART + ISSUES + OVERVIEW ===================== -->
    <section class="pdf-page">
      ${headerHTML(reportId, 2)}

      <div class="pdf-h">Score progression</div>
      <div class="pdf-chart-wrap">
        <div class="pdf-chart-h">
          <span>Trending up · 3 analyses since baseline</span>
          <span class="pdf-legend">
            <span class="pdf-legend-item"><span class="pdf-legend-dot" style="background:#2E7D5A"></span>Health score</span>
            <span class="pdf-legend-item"><span class="pdf-legend-dot" style="background:#B85C9C"></span>Bio age (yrs younger)</span>
          </span>
        </div>
        ${progressChartSVG()}
      </div>

      <div class="pdf-h">Biomarker status</div>
      <div class="pdf-bio-status-h">
        <span style="font-family:'Inter';font-size:13px;color:#555;">Flagged biomarkers requiring follow-up</span>
        <span class="pdf-count"><strong>21 of 27</strong> in optimal range</span>
      </div>
      <div class="pdf-issues">
        ${issue('att',  'Creatinine',         '1.31 mg/dL',  'High — trending up')}
        ${issue('bord', 'Lp(a)',              '128 nmol/L',  'Elevated — genetic CV risk')}
        ${issue('bord', 'Free testosterone',  '23.5 pg/mL',  'Declining significantly')}
        ${issue('bord', 'MCV',                '98 fL',       'At upper edge of normal')}
        ${issue('bord', 'T3RU',               '52%',         'Slightly elevated')}
        ${issue('info', 'Insulin',            '2.3 µIU/mL',  'Low — below typical range')}
      </div>

      <div class="pdf-h" style="margin-top:24px;">Overall snapshot</div>
      <div class="pdf-narr-section">
        <p class="pdf-narr-p">
          Your longitudinal labs show <strong>strong overall health</strong> with most biomarkers consistently within normal ranges across testing from October 2025 through May 2026. Excellent metabolic control, healthy lipids, and stable blood counts. Six markers warrant a closer look and are detailed in the sections that follow.
        </p>
      </div>

      ${pageFooter(2, 5, reportId, generatedAt)}
    </section>

    <!-- ===================== PAGE 3: NARRATIVE PART 1 ===================== -->
    <section class="pdf-page">
      ${headerHTML(reportId, 3)}

      <div class="pdf-h">Clinical narrative <span class="right">Generated by ApexAI · Reviewed by Jim Bowen, MD</span></div>

      <div class="pdf-narr-section">
        <div class="pdf-narr-h">Metabolic health <span class="pdf-narr-status bord">● Watch insulin</span></div>
        <p class="pdf-narr-p">
          Glucose metabolism remains excellent — fasting glucose steady at <span class="val">89 → 88 mg/dL</span> and HbA1c at <span class="val">5.1 → 5.2%</span> across both dates. Insulin dropped from <span class="val">8.6 to 2.3 µIU/mL</span> (now Low), worth a conversation with Dr. Patel to confirm adequate pancreatic function. HOMA-IR of 1.9 still indicates good insulin sensitivity.
        </p>
        <div class="pdf-explain">
          <div class="pdf-explain-h">What this means in plain terms</div>
          ${explainItem('Glucose', '70–99 mg/dL', 'Your blood sugar after fasting overnight. At 88, your body handles sugar well — no concern about diabetes.')}
          ${explainItem('HbA1c', '<5.7%', 'Average blood sugar over the past three months. Yours at 5.2% is solidly in the healthy range.')}
          ${explainItem('Insulin', '2.6–25 µIU/mL', 'How much insulin your pancreas releases at rest. Yours dropped to 2.3, just below typical. Often a positive sign of insulin sensitivity, but worth confirming with Dr. Patel that pancreatic function is normal.')}
          ${explainItem('HOMA-IR', '<2.0 ideal', 'A calculated score for how well your cells respond to insulin. At 1.9, your body uses sugar efficiently — no insulin resistance.')}
        </div>
      </div>

      <div class="pdf-narr-section">
        <div class="pdf-narr-h">Lipid panel &amp; cardiovascular <span class="pdf-narr-status bord">● Elevated Lp(a)</span></div>
        <p class="pdf-narr-p">
          Lipid profile is favorable overall. Total cholesterol rose modestly from <span class="val">137 to 149 mg/dL</span>, LDL from <span class="val">68 to 91 mg/dL</span> — all still in healthy range. HDL drifted from <span class="val">55 to 50 mg/dL</span> and triglycerides held low. <strong>Lp(a) at 128 nmol/L</strong> is elevated — a genetic marker that adds cardiovascular risk independent of LDL, worth a preventive-strategy conversation. CRP remains low, indicating minimal inflammation.
        </p>
        <div class="pdf-explain">
          <div class="pdf-explain-h">What this means in plain terms</div>
          ${explainItem('Total cholesterol', '<200 mg/dL', 'All forms of cholesterol combined. Yours at 149 is excellent.')}
          ${explainItem('LDL ("bad" cholesterol)', '<100 mg/dL', 'The cholesterol that can build up inside artery walls. Yours at 91 is in the healthy range.')}
          ${explainItem('HDL ("good" cholesterol)', '>40 mg/dL men', 'Helps remove bad cholesterol from arteries. Yours at 50 is healthy.')}
          ${explainItem('Triglycerides', '<150 mg/dL', 'A type of fat in your blood from food and made by your liver. Yours at 51 is excellent.')}
          ${explainItem('Lp(a)', '<75 nmol/L', 'A genetic form of cholesterol you mostly cannot change with diet or exercise. Yours at 128 is elevated and independently raises heart disease risk — worth a prevention strategy with your doctor (often more aggressive LDL targets).')}
          ${explainItem('CRP', '<1 mg/L low risk', 'A marker of inflammation. Yours is <1, meaning very little inflammation — good for cardiovascular health.')}
        </div>
      </div>

      <div class="pdf-narr-section">
        <div class="pdf-narr-h">Kidney function <span class="pdf-narr-status bord">● Trending up</span></div>
        <p class="pdf-narr-p">
          Creatinine has risen from <span class="val">1.2 to 1.31 mg/dL</span>, though eGFR remains stable around <span class="val">75–83 mL/min/1.73m²</span> and BUN/Cr ratio is normal. The mild elevation may reflect increased muscle mass or hydration status rather than reduced filtration — worth tracking across the next two panels.
        </p>
        <div class="pdf-explain">
          <div class="pdf-explain-h">What this means in plain terms</div>
          ${explainItem('Creatinine', '0.74–1.35 mg/dL', 'A waste product from muscle breakdown that your kidneys filter out. Yours at 1.31 is at the upper edge of normal and trending up. Can also reflect more muscle mass or being dehydrated at the draw.')}
          ${explainItem('eGFR', '>60 mL/min', 'An estimate of how well your kidneys filter waste. Yours at 75–83 is healthy.')}
          ${explainItem('BUN/Cr ratio', '10–20', 'Normal ratio (yours is 11) suggests dehydration or other factors are not skewing your creatinine result.')}
        </div>
      </div>

      ${pageFooter(3, 5, reportId, generatedAt)}
    </section>

    <!-- ===================== PAGE 4: NARRATIVE PART 2 + DISCLAIMER ===================== -->
    <section class="pdf-page">
      ${headerHTML(reportId, 4)}

      <div class="pdf-h">Clinical narrative <span class="right">continued</span></div>

      <div class="pdf-narr-section">
        <div class="pdf-narr-h">Blood count &amp; thyroid <span class="pdf-narr-status opt">● Mostly optimal</span></div>
        <p class="pdf-narr-p">
          CBC markers are stable — hemoglobin, hematocrit, and WBC all within range. <strong>MCV mildly elevated at 98 fL</strong> could suggest macrocytosis (often benign, sometimes related to B12 or folate — both of yours are excellent). Thyroid function is excellent: TSH and Free T4 are well-balanced. T3RU slightly high at 52% but Free T4 stays normal, likely not clinically significant.
        </p>
        <div class="pdf-explain">
          <div class="pdf-explain-h">What this means in plain terms</div>
          ${explainItem('Hemoglobin (Hgb)', '13.5–17.5 g/dL men', 'The oxygen-carrying protein in your red blood cells. Yours at 14.2–14.6 means your blood carries oxygen well.')}
          ${explainItem('MCV', '80–100 fL', 'The average size of your red blood cells. Yours at 98 is at the upper edge — slightly large cells can occasionally point to low B12/folate, but yours are both excellent.')}
          ${explainItem('TSH', '0.4–4.0 mIU/L', 'The hormone that tells your thyroid how hard to work. Yours at 2.5–3.0 is balanced.')}
          ${explainItem('Free T4', '0.8–1.8 ng/dL', 'The main thyroid hormone available for your body to use. Yours is normal.')}
        </div>
      </div>

      <div class="pdf-narr-section">
        <div class="pdf-narr-h">Hormones <span class="pdf-narr-status bord">● Discuss with provider</span></div>
        <p class="pdf-narr-p">
          Total testosterone improved nicely from <span class="val">530 to 628 ng/dL</span>, but <strong>free testosterone dropped from 85.9 to 23.5 pg/mL</strong> — a significant decline. SHBG rose from <span class="val">32 to 39.4 nmol/L</span>, which partly explains the lower free fraction. LH dropped from <span class="val">7.3 to 3.8 mIU/mL</span>. These hormonal-axis shifts merit a focused conversation with your physician.
        </p>
        <div class="pdf-explain">
          <div class="pdf-explain-h">What this means in plain terms</div>
          ${explainItem('Total testosterone', '264–916 ng/dL men', 'The total testosterone in your blood. Yours at 628 is solidly in normal range and improved from prior.')}
          ${explainItem('Free testosterone', '8.7–25.1 pg/mL men', 'The "active" portion your body uses. Yours dropped to 23.5 — still in range, but the drop from 85.9 is significant. Can affect energy, libido, muscle, mood. Worth a focused conversation.')}
          ${explainItem('SHBG', '16.5–55.9 nmol/L', 'A protein that binds testosterone. Yours rose to 39.4, partly explaining lower free T.')}
        </div>
      </div>

      <div class="pdf-narr-section">
        <div class="pdf-narr-h">Micronutrients &amp; liver <span class="pdf-narr-status opt">● All optimal</span></div>
        <p class="pdf-narr-p">
          Vitamin D optimal at <span class="val">51 ng/mL</span>. B12 and folate excellent. Iron stores well-maintained — ferritin <span class="val">127 ng/mL</span> and serum iron in healthy range. Liver enzymes (ALT, AST, ALP, bilirubin) all normal, reflecting good hepatic function.
        </p>
        <div class="pdf-explain">
          <div class="pdf-explain-h">What this means in plain terms</div>
          ${explainItem('Vitamin D', '40–80 ng/mL optimal', 'Critical for bone, immune, and mood. Yours at 51 is optimal.')}
          ${explainItem('B12', '232–1245 pg/mL', 'Needed for nerves, energy, red blood cells. Yours at 996 is excellent.')}
          ${explainItem('Ferritin', '30–400 ng/mL men', 'Your iron storage protein. Yours at 127 is healthy.')}
        </div>
      </div>

      <div class="pdf-disclaimer">
        <strong>Clinical disclaimer.</strong> This analysis is generated by ApexAI from laboratory results and is intended as a longitudinal reference summary for your physician. It does not constitute medical diagnosis or treatment. Reference ranges are population-derived and may differ from your laboratory's reported ranges. All flagged biomarkers should be reviewed with your ordering provider before any change in medication, supplementation, or lifestyle. PhenoAge biological age is calculated per Levine et al., <em>Aging</em>, 2018, using 9 standard biomarkers plus chronological age. Single-analysis biological age values may vary by 1–2 years between draws due to normal lab variability.
      </div>

      ${pageFooter(4, 5, reportId, generatedAt)}
    </section>

    <!-- ===================== PAGE 5: RECOMMENDATIONS + CONCIERGE ===================== -->
    <section class="pdf-page">
      ${headerHTML(reportId, 5)}

      <div class="pdf-h">Recommended for you <span class="right">Curated from your genetic gauges</span></div>

      <div class="pdf-reco-label">Top 3 supplements</div>
      <div class="pdf-reco-grid">
        ${recoItem(_thumbs[0], 'RED Superfood', 'Immune function \u00b7 Gut health \u00b7 Antioxidant defense', '$39.99', '', '')}
        ${recoItem(_thumbs[1], 'Probiotic \u2014 40 Billion CFU', 'Digestive health \u00b7 Microbiome balance \u00b7 Immune health', '$34.99', '', '')}
        ${recoItem(_thumbs[2], 'Vitamin K2 + D3', 'Strong bones \u00b7 Cardiovascular health \u00b7 Immune function', '$29.99', '', '')}
      </div>

      <div class="pdf-reco-label">Recommended peptide</div>
      <div class="pdf-reco-grid">
        ${recoItem(_thumbs[3], 'Wolverine Stack', 'BPC-157 + TB-500 \u00b7 Tissue &amp; joint repair \u00b7 Inflammation resolution \u00b7 Recovery', '$249', 'peptide', 'Your Peptides 1.0 panel returns an increased genetic benefit for both halves \u2014 BPC-157 for inflammation resolution and pain burden, TB-500 for tissue and connective-tissue repair \u2014 the cleaner genetic fit for a repair-and-resolution stack.')}
      </div>

      <div class="pdf-reco-also"><strong>Also strong in your report:</strong> Thymosin \u03b1-1 (immune support) \u00b7 Semax (cognitive performance) \u00b7 Epitalon (general longevity) \u00b7 GHK-Cu (skin aging &amp; collagen)</div>

      <div class="pdf-h" style="margin-top:22px;">Work with Apex MD</div>
      <div class="pdf-concierge">
        <div class="pdf-concierge-photo"><img src="${_docPhoto}" alt="Apex MD physician with a patient"></div>
        <div class="pdf-concierge-body">
          <div class="pdf-concierge-eyebrow">Concierge medicine</div>
          <div class="pdf-concierge-title">Work directly with an Apex MD physician \u2014 virtually</div>
          <div class="pdf-concierge-text">Take the next step beyond your report. Get a personalized health optimization plan and work one-on-one with an Apex MD physician \u2014 with regular blood draws and advanced diagnostic testing to ensure optimal health is restored and maintained.</div>
          <div class="pdf-concierge-price">Starting at <strong>$399</strong>/month \u00b7 Book a consultation through your Apex MD care team</div>
        </div>
      </div>

      ${pageFooter(5, 5, reportId, generatedAt)}
    </section>

    `;
  }

  // -------- HTML helpers --------
  function headerHTML(reportId, pageNum) {
    return `
      <div class="pdf-header">
        <div class="pdf-brand">
          <img class="pdf-brand-logo" src="assets/img/apex-md-logo-report.png" alt="Apex MD">
          <div class="pdf-brand-tag">Concierge longevity medicine</div>
        </div>
        <div class="pdf-header-meta">
          <strong>HEALTH ANALYSIS</strong>
          Report ${reportId}<br>
          Issued May 12, 2026<br>
          Page ${pageNum} of 5
        </div>
      </div>
    `;
  }

  function donutSVG(score) {
    const r = 70;
    const c = 2 * Math.PI * r;
    const filled = (score / 100) * c;
    return `
      <svg viewBox="0 0 180 180">
        <circle cx="90" cy="90" r="${r}" fill="none" stroke="#EAEAE7" stroke-width="12"/>
        <circle cx="90" cy="90" r="${r}" fill="none" stroke="#2E7D5A" stroke-width="12"
                stroke-dasharray="${filled} ${c}" stroke-linecap="round"
                transform="rotate(-90 90 90)"/>
        <text x="90" y="98" text-anchor="middle"
              font-family="JetBrains Mono, monospace" font-size="48" font-weight="700"
              fill="#1A1A1A" letter-spacing="-2">${score}</text>
        <text x="90" y="118" text-anchor="middle"
              font-family="JetBrains Mono, monospace" font-size="10"
              fill="#888" letter-spacing="1">/ 100</text>
      </svg>
    `;
  }

  function bdownRow(name, val, cls = '') {
    return `
      <div class="pdf-bdown-row ${cls}">
        <span class="pdf-bdown-name">${name}</span>
        <span class="pdf-bdown-val">${val}</span>
        <div class="pdf-bdown-bar"><div class="pdf-bdown-fill" style="width:${val}%"></div></div>
      </div>
    `;
  }

  function issue(cls, name, val, status) {
    return `
      <div class="pdf-issue ${cls}">
        <span class="pdf-issue-dot"></span>
        <span class="pdf-issue-name">${name}</span>
        <span class="pdf-issue-val">${val}</span>
        <span class="pdf-issue-status">${status}</span>
      </div>
    `;
  }

  function explainItem(name, range, text) {
    return `
      <div class="pdf-explain-item">
        <strong>${name}</strong><span class="range">${range}</span>${text}
      </div>
    `;
  }

  function recoItem(img, name, tag, price, extraClass, desc) {
    return `
      <div class="pdf-reco-item ${extraClass || ''}">
        <div class="pdf-reco-thumb"><img src="${img}" alt=""></div>
        <div class="pdf-reco-meta">
          <div class="pdf-reco-name">${name}</div>
          <div class="pdf-reco-tag">${tag}</div>
          ${desc ? `<div class="pdf-reco-desc">${desc}</div>` : ''}
        </div>
        <div class="pdf-reco-price">${price}</div>
      </div>
    `;
  }

  function pageFooter(pageNum, totalPages, reportId, generated) {
    return `
      <div class="pdf-page-footer">
        <span>ApexMD · Health Analysis · ${reportId}</span>
        <span>Page ${pageNum} / ${totalPages} · Generated ${generated}</span>
      </div>
    `;
  }

  function progressChartSVG() {
    // Chart area: x 60 to 720 (660 wide), y 24 to 150 (126 tall)
    // Three points evenly spaced
    // Score: May 4 = 88 (y=87), May 6 = 88 (y=87), May 11 = 89 (y=71)
    // Bio age: -3.4 (y=74), -3.5 (y=66), -3.6 (y=58)
    return `
      <svg class="pdf-chart-svg" viewBox="0 0 760 200" preserveAspectRatio="xMidYMid meet">
        <!-- Y gridlines -->
        <g stroke="#EAEAE7" stroke-width="1">
          <line x1="60" y1="24" x2="720" y2="24"/>
          <line x1="60" y1="56" x2="720" y2="56"/>
          <line x1="60" y1="87" x2="720" y2="87"/>
          <line x1="60" y1="119" x2="720" y2="119"/>
          <line x1="60" y1="150" x2="720" y2="150"/>
        </g>
        <!-- Y labels -->
        <g font-family="Inter, sans-serif" font-size="10" fill="#888" text-anchor="end">
          <text x="54" y="28">92</text>
          <text x="54" y="60">90</text>
          <text x="54" y="91">88</text>
          <text x="54" y="123">86</text>
          <text x="54" y="154">84</text>
        </g>
        <!-- X axis -->
        <g font-family="Inter, sans-serif" font-size="11" fill="#444" text-anchor="middle" font-weight="600">
          <text x="160" y="172">May 4</text>
          <text x="400" y="172">May 6</text>
          <text x="660" y="172">May 11</text>
        </g>
        <g font-family="Inter, sans-serif" font-size="9.5" fill="#888" text-anchor="middle">
          <text x="160" y="186">3:03 PM</text>
          <text x="400" y="186">8:40 AM</text>
          <text x="660" y="186">6:26 AM</text>
        </g>
        <!-- Area fill -->
        <path d="M 160,87 L 400,87 L 660,71 L 660,150 L 160,150 Z" fill="rgba(46,125,90,0.10)"/>
        <!-- Score line -->
        <polyline points="160,87 400,87 660,71"
                  fill="none" stroke="#2E7D5A" stroke-width="2.5"
                  stroke-linejoin="round" stroke-linecap="round"/>
        <g>
          <circle cx="160" cy="87" r="5.5" fill="#fff" stroke="#2E7D5A" stroke-width="2.5"/>
          <text x="160" y="76" font-family="JetBrains Mono, monospace" font-size="12"
                fill="#2E7D5A" font-weight="700" text-anchor="middle">88</text>
          <circle cx="400" cy="87" r="5.5" fill="#fff" stroke="#2E7D5A" stroke-width="2.5"/>
          <text x="400" y="76" font-family="JetBrains Mono, monospace" font-size="12"
                fill="#2E7D5A" font-weight="700" text-anchor="middle">88</text>
          <circle cx="660" cy="71" r="6.5" fill="#2E7D5A" stroke="#fff" stroke-width="2.5"/>
          <text x="660" y="59" font-family="JetBrains Mono, monospace" font-size="13"
                fill="#2E7D5A" font-weight="700" text-anchor="middle">89</text>
        </g>
        <!-- Bio age dashed -->
        <polyline points="160,74 400,66 660,58"
                  fill="none" stroke="#B85C9C" stroke-width="2"
                  stroke-linejoin="round" stroke-linecap="round"
                  stroke-dasharray="5,4" opacity="0.75"/>
        <g>
          <circle cx="160" cy="74" r="4" fill="#fff" stroke="#B85C9C" stroke-width="2"/>
          <circle cx="400" cy="66" r="4" fill="#fff" stroke="#B85C9C" stroke-width="2"/>
          <circle cx="660" cy="58" r="5" fill="#B85C9C" stroke="#fff" stroke-width="2"/>
        </g>
        <g font-family="JetBrains Mono, monospace" font-size="9.5" fill="#B85C9C" font-weight="600" text-anchor="middle">
          <text x="160" y="62">−3.4y</text>
          <text x="400" y="54">−3.5y</text>
          <text x="660" y="46">−3.6y</text>
        </g>
      </svg>
    `;
  }

  // -------- Modal open/close --------
  function openPdfModal() {
    buildReport();
    const m = document.getElementById('exportPdfModal');
    m.classList.add('open');
    m.setAttribute('aria-hidden', 'false');
    document.body.style.overflow = 'hidden';
  }
  function closePdfModal() {
    const m = document.getElementById('exportPdfModal');
    m.classList.remove('open');
    m.setAttribute('aria-hidden', 'true');
    document.body.style.overflow = '';
  }

  // Wire up
  document.getElementById('exportPdfBtn').addEventListener('click', openPdfModal);
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && document.getElementById('exportPdfModal').classList.contains('open')) {
      closePdfModal();
    }
  });
  document.querySelector('.pdf-modal-overlay').addEventListener('click', closePdfModal);
