#!/usr/bin/env node
/* Bundles every data/*.json file into js/data.js as window.APEX_DATA.
 * Loading data as a <script> (instead of fetch) lets index.html run over file://.
 * Run: node tools/build-data.js
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dataDir = path.join(root, 'data');
const outFile = path.join(root, 'js', 'data.js');

const bundle = {};
for (const file of fs.readdirSync(dataDir).sort()) {
  if (!file.endsWith('.json')) continue;
  const key = path.basename(file, '.json');
  bundle[key] = JSON.parse(fs.readFileSync(path.join(dataDir, file), 'utf8'));
}

const banner = '/* AUTO-GENERATED by tools/build-data.js — edit data/*.json, not this file. */\n';
fs.writeFileSync(outFile, banner + 'window.APEX_DATA = ' + JSON.stringify(bundle, null, 2) + ';\n');
console.log('Wrote js/data.js from', Object.keys(bundle).join(', '));
