/* AUTO-GENERATED by tools/build-data.js — edit data/*.json, not this file. */
window.APEX_DATA = {
  "icons": {
    "layout-dashboard": "<path d=\"M5 4h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1\" /> <path d=\"M5 16h4a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1\" /> <path d=\"M15 12h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1\" /> <path d=\"M15 4h4a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1\" />",
    "sparkles": "<path d=\"M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m0 -12a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m-7 12a6 6 0 0 1 6 -6a6 6 0 0 1 -6 -6a6 6 0 0 1 -6 6a6 6 0 0 1 6 6\" />",
    "pill": "<path d=\"M4.5 12.5l8 -8a4.94 4.94 0 0 1 7 7l-8 8a4.94 4.94 0 0 1 -7 -7\" /> <path d=\"M8.5 8.5l7 7\" />",
    "message-circle": "<path d=\"M3 20l1.3 -3.9c-2.324 -3.437 -1.426 -7.872 2.1 -10.374c3.526 -2.501 8.59 -2.296 11.845 .48c3.255 2.777 3.695 7.266 1.029 10.501c-2.666 3.235 -7.615 4.215 -11.574 2.293l-4.7 1\" />",
    "flask-2": "<path d=\"M6.1 15h11.8\" /> <path d=\"M14 3v7.342a6 6 0 0 1 1.318 10.658h-6.635a6 6 0 0 1 1.317 -10.66v-7.34h4\" /> <path d=\"M9 3h6\" />",
    "dna-2": "<path d=\"M17 3v1c-.01 3.352 -1.68 6.023 -5.008 8.014c-3.328 1.99 3.336 -2 .008 -.014c-3.328 1.99 -5 4.662 -5.008 8.014v1\" /> <path d=\"M17 21.014v-1c-.01 -3.352 -1.68 -6.023 -5.008 -8.014c-3.328 -1.99 3.336 2 .008 .014c-3.328 -1.991 -5 -4.662 -5.008 -8.014v-1\" /> <path d=\"M7 4h10\" /> <path d=\"M7 20h10\" /> <path d=\"M8 8h8\" /> <path d=\"M8 16h8\" />",
    "trending-up": "<path d=\"M3 17l6 -6l4 4l8 -8\" /> <path d=\"M14 7l7 0l0 7\" />",
    "test-pipe": "<path d=\"M20 8.04l-12.122 12.124a2.857 2.857 0 1 1 -4.041 -4.04l12.122 -12.124\" /> <path d=\"M7 13h8\" /> <path d=\"M19 15l1.5 1.6a2 2 0 1 1 -3 0l1.5 -1.6\" /> <path d=\"M15 3l6 6\" />",
    "shopping-bag": "<path d=\"M6.331 8h11.339a2 2 0 0 1 1.977 2.304l-1.255 8.152a3 3 0 0 1 -2.966 2.544h-6.852a3 3 0 0 1 -2.965 -2.544l-1.255 -8.152a2 2 0 0 1 1.977 -2.304\" /> <path d=\"M9 11v-5a3 3 0 0 1 6 0v5\" />",
    "school": "<path d=\"M22 9l-10 -4l-10 4l10 4l10 -4v6\" /> <path d=\"M6 10.6v5.4a6 3 0 0 0 12 0v-5.4\" />",
    "user-circle": "<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /> <path d=\"M9 10a3 3 0 1 0 6 0a3 3 0 1 0 -6 0\" /> <path d=\"M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855\" />",
    "clipboard-check": "<path d=\"M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2\" /> <path d=\"M9 5a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2\" /> <path d=\"M9 14l2 2l4 -4\" />",
    "barbell": "<path d=\"M2 12h1\" /> <path d=\"M6 8h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2\" /> <path d=\"M6 7v10a1 1 0 0 0 1 1h1a1 1 0 0 0 1 -1v-10a1 1 0 0 0 -1 -1h-1a1 1 0 0 0 -1 1\" /> <path d=\"M9 12h6\" /> <path d=\"M15 7v10a1 1 0 0 0 1 1h1a1 1 0 0 0 1 -1v-10a1 1 0 0 0 -1 -1h-1a1 1 0 0 0 -1 1\" /> <path d=\"M18 8h2a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-2\" /> <path d=\"M22 12h-1\" />",
    "apple": "<path d=\"M4 11.319c0 3.102 .444 5.319 2.222 7.978c1.351 1.797 3.156 2.247 5.08 .988c.426 -.268 .97 -.268 1.397 0c1.923 1.26 3.728 .809 5.079 -.988c1.778 -2.66 2.222 -4.876 2.222 -7.977c0 -2.661 -1.99 -5.32 -4.444 -5.32c-1.267 0 -2.41 .693 -3.22 1.44a.5 .5 0 0 1 -.672 0c-.809 -.746 -1.953 -1.44 -3.22 -1.44c-2.454 0 -4.444 2.66 -4.444 5.319\" /> <path d=\"M7 12c0 -1.47 .454 -2.34 1.5 -3\" /> <path d=\"M12 7c0 -1.2 .867 -4 3 -4\" />",
    "refresh": "<path d=\"M20 11a8.1 8.1 0 0 0 -15.5 -2m-.5 -4v4h4\" /> <path d=\"M4 13a8.1 8.1 0 0 0 15.5 2m.5 4v-4h-4\" />",
    "message-2": "<path d=\"M8 9h8\" /> <path d=\"M8 13h6\" /> <path d=\"M9 18h-3a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-3l-3 3l-3 -3\" />",
    "truck": "<path d=\"M5 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /> <path d=\"M15 17a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /> <path d=\"M5 17h-2v-11a1 1 0 0 1 1 -1h9v12m-4 0h6m4 0h2v-6h-8m0 -5h5l3 5\" />",
    "chart-bar": "<path d=\"M3 13a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -6\" /> <path d=\"M15 9a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -10\" /> <path d=\"M9 5a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -14\" /> <path d=\"M4 20h14\" />",
    "search": "<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /> <path d=\"M21 21l-6 -6\" />",
    "shopping-cart": "<path d=\"M4 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /> <path d=\"M15 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /> <path d=\"M17 17h-11v-14h-2\" /> <path d=\"M6 5l14 1l-1 7h-13\" />",
    "chevron-right": "<path d=\"M9 6l6 6l-6 6\" />",
    "package": "<path d=\"M12 3l8 4.5l0 9l-8 4.5l-8 -4.5l0 -9l8 -4.5\" /> <path d=\"M12 12l8 -4.5\" /> <path d=\"M12 12l0 9\" /> <path d=\"M12 12l-8 -4.5\" /> <path d=\"M16 5.25l-8 4.5\" />",
    "dna": "<path d=\"M14.828 14.828a4 4 0 1 0 -5.656 -5.656a4 4 0 0 0 5.656 5.656\" /> <path d=\"M9.172 20.485a4 4 0 1 0 -5.657 -5.657\" /> <path d=\"M14.828 3.515a4 4 0 0 0 5.657 5.657\" />"
  },
  "kits": [
    {
      "key": "blood",
      "image": "blood.jpg",
      "eyebrow": "100+ biomarkers",
      "title": "Comprehensive Blood Work",
      "desc": "A full read on metabolic health, cardiovascular risk, hormones, thyroid, inflammation, and organ function — the complete picture of how your body is working right now. Drawn at home, reviewed by your physician.",
      "price": "from $249"
    },
    {
      "key": "genetics",
      "image": "genetics.jpg",
      "eyebrow": "DNA insights",
      "title": "Genetics Testing",
      "desc": "Your DNA reveals how you metabolize nutrients, medications, and caffeine, your predisposition to certain conditions, and the supplement and lifestyle strategies most likely to work for your unique makeup.",
      "price": "$399"
    },
    {
      "key": "bioage",
      "image": "bioage.jpg",
      "eyebrow": "Cellular age",
      "title": "Biological Age Test",
      "desc": "Your age is just a number. We measure how old your cells actually are using epigenetic and biomarker analysis, then track it over time to prove your protocol is making you biologically younger.",
      "price": "$399"
    },
    {
      "key": "microbiome",
      "image": "microbiome.jpg",
      "eyebrow": "Gut health",
      "title": "Microbiome Testing",
      "desc": "A deep look at your gut — bacterial diversity, intestinal permeability, digestion and absorption, inflammation, and SIBO — the foundation of your immunity, mood, metabolism, and overall health.",
      "price": "$399"
    },
    {
      "key": "micronutrient",
      "image": "micronutrient.jpg",
      "eyebrow": "Vitamins & minerals",
      "title": "Micronutrient Testing",
      "desc": "We measure the vitamins, minerals, antioxidants, amino acids, and omega-3/6 fatty acids inside your cells — pinpointing exactly what your body is missing so supplementation is precise, not guesswork.",
      "price": "$399"
    },
    {
      "key": "foodsens",
      "image": "foodsens.jpg",
      "eyebrow": "Trigger foods",
      "title": "Food Sensitivity Test",
      "desc": "Identifies the foods quietly triggering inflammation, bloating, fatigue, and skin or gut issues — so your nutrition plan is built around what fuels you and free of what holds you back.",
      "price": "$399"
    }
  ],
  "member": {
    "name": "Robert Carlsen",
    "initials": "RC",
    "meta": "MRN 04821 · Concierge · 40 yrs"
  },
  "nav": {
    "menuLabel": "Menu",
    "groups": [
      {
        "brand": "apex-md-logo.png",
        "brandAlt": "Apex MD",
        "brandClass": "",
        "items": [
          {
            "label": "Dashboard",
            "icon": "layout-dashboard"
          },
          {
            "label": "Health Analysis",
            "icon": "sparkles"
          },
          {
            "label": "My Treatments",
            "icon": "pill"
          },
          {
            "label": "Chat",
            "icon": "message-circle"
          },
          {
            "label": "Biomarkers",
            "icon": "flask-2"
          },
          {
            "label": "Genetics",
            "icon": "dna-2"
          },
          {
            "label": "Progress",
            "icon": "trending-up"
          },
          {
            "label": "Lab Kits",
            "icon": "test-pipe",
            "active": true
          },
          {
            "label": "Shop",
            "icon": "shopping-bag"
          },
          {
            "label": "Education",
            "icon": "school"
          },
          {
            "label": "Profile",
            "icon": "user-circle"
          }
        ]
      },
      {
        "brand": "apex-fit-logo.png",
        "brandAlt": "Apex Fit",
        "brandClass": "brand-fit",
        "items": [
          {
            "label": "Program",
            "icon": "clipboard-check"
          },
          {
            "label": "Workouts",
            "icon": "barbell"
          },
          {
            "label": "Nutrition",
            "icon": "apple"
          },
          {
            "label": "Habits",
            "icon": "refresh"
          },
          {
            "label": "Trainer Messages",
            "icon": "message-2"
          }
        ]
      }
    ]
  },
  "page": {
    "crumbRoot": "Apex MD",
    "crumbHere": "Lab Kits",
    "titleLead": "Lab",
    "titleAccent": "kits",
    "sub": "Physician-reviewed at-home diagnostics. Collect your sample at home, we handle the lab and read every result back to you.",
    "searchPlaceholder": "Search records, protocols, programs…"
  }
};
