#!/usr/bin/env node
/* build-data.js
 * Bundles data/*.json into js/data.js as `window.APEX_DATA`.
 * Browsers can't fetch local JSON over file://, so the page loads this
 * generated bundle via a <script> tag instead. Re-run after editing any
 * file in /data.
 *
 *   node tools/build-data.js
 */
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = (f) => JSON.parse(fs.readFileSync(path.join(root, "data", f), "utf8"));

const data = {
  profile: read("profile.json"),
  inbox: read("inbox.json"),
  conversation: read("conversation.json"),
};

const banner =
  "/* AUTO-GENERATED by tools/build-data.js — do not edit by hand.\n" +
  "   Edit the source files in /data and re-run `node tools/build-data.js`. */\n";

const out = banner + "window.APEX_DATA = " + JSON.stringify(data, null, 2) + ";\n";
fs.writeFileSync(path.join(root, "js", "data.js"), out);
console.log("Wrote js/data.js (" + out.length + " bytes)");
